 SELECT        C.CUST_ID,   C.CUST_CD,   NVL(CUST_TRNSLT_NM,C.CUST_DESC_TXT) AS CUST_TRNSLT_NM,   CA.CUST_REF_ID, 
 ASR.APPL_SYS_CD,   C.CUST_DESC_TXT  ,    NVL(ACC_ROLE_TRNSLTN_NM, ACC_ROLE_EXTRNL_NM) AS ACC_ROLE_EXTRNL_NM,  
 ACCESS_ROLE_INTERNAL_NM,    'N' AS ASSIGNED   FROM CUST C      LEFT JOIN CUST_NM_TRNSLTN CT ON 
 C.CUST_ID = CT.CUST_ID AND SYS_EXTRACT_UTC(SYSTIMESTAMP)  BETWEEN CT.EFF_START_TS AND CT.EFF_END_TS AND CT.LANG_ID = 1 
 LEFT JOIN CUST_APPL_SYS_ALIAS CA ON C.CUST_ID = CA.CUST_ID AND SYS_EXTRACT_UTC(SYSTIMESTAMP)  BETWEEN CA.EFF_START_TS AND CA.EFF_END_TS  
 LEFT JOIN APPL_SYS_REF ASR ON CA.APPL_SYS_ID = ASR.APPL_SYS_ID AND SYS_EXTRACT_UTC(SYSTIMESTAMP)  BETWEEN ASR.EFF_START_TS AND ASR.EFF_END_TS 
 LEFT JOIN CUST_ACC_ROLE_ASSN CARA ON SYS_EXTRACT_UTC(SYSTIMESTAMP) BETWEEN CARA.EFF_START_TS AND CARA.EFF_END_TS AND C.CUST_ID = CARA.CUST_ID 
 JOIN ACCESS_ROLE AR ON AR.ACCESS_ROLE_ID = CARA.ACCESS_ROLE_ID AND SYS_EXTRACT_UTC(SYSTIMESTAMP) BETWEEN AR.EFF_START_TS AND AR.EFF_END_TS
 LEFT OUTER JOIN ACC_ROLE_EXTRNL_NM_TRNSLTN ARENT ON CARA.CUST_ACC_ROLE_ASSN_ID = ARENT.CUST_ACC_ROLE_ASSN_ID    AND SYS_EXTRACT_UTC(SYSTIMESTAMP)
 BETWEEN ARENT.EFF_START_TS AND ARENT.EFF_END_TS AND ARENT.LANG_ID = 1   WHERE SYS_EXTRACT_UTC(SYSTIMESTAMP) BETWEEN C.EFF_START_TS 
 AND C.EFF_END_TS 